BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS USERS (
    id UUID PRIMARY KEY,
    phone_number VARCHAR UNIQUE,
    name VARCHAR,
    password VARCHAR,
    created_at BIGINT DEFAULT EXTRACT(EPOCH FROM NOW())
);

CREATE TABLE IF NOT EXISTS products (
    id SERIAL PRIMARY KEY,
    user_id UUID REFERENCES USERS(id) ON DELETE CASCADE,
    name VARCHAR NOT NULL,
    sku VARCHAR NOT NULL,
    category VARCHAR NOT NULL,
    image_url VARCHAR NOT NULL,
    notes VARCHAR NOT NULL,
    price DECIMAL NOT NULL,
    stock INTEGER NOT NULL,
    location VARCHAR NOT NULL,
    is_available BOOLEAN DEFAULT TRUE,
    created_at BIGINT DEFAULT EXTRACT(EPOCH FROM NOW())
);

CREATE TABLE IF NOT EXISTS customers (
    id SERIAL PRIMARY KEY,
    staff_id UUID REFERENCES USERS(id) ON DELETE CASCADE,
    phone_number VARCHAR UNIQUE,
    name VARCHAR NOT NULL,
    created_at BIGINT DEFAULT EXTRACT(EPOCH FROM NOW())
);

CREATE TABLE IF NOT EXISTS transactions (
    id SERIAL PRIMARY KEY,
    customer_id INTEGER REFERENCES customers(id) ON DELETE CASCADE,
    paid DECIMAL NOT NULL,
    change DECIMAL NOT NULL,
    created_at BIGINT DEFAULT EXTRACT(EPOCH FROM NOW())
);

CREATE TABLE IF NOT EXISTS transaction_details (
    id SERIAL PRIMARY KEY,
    order_id INTEGER REFERENCES transactions(id) ON DELETE CASCADE,
    product_id INTEGER REFERENCES products(id) ON DELETE CASCADE,
    quantity INTEGER NOT NULL,
    created_at BIGINT DEFAULT EXTRACT(EPOCH FROM NOW())
);

COMMIT TRANSACTION;